bindel = Alt ,F4 ,exec ,$scrPath/dontkillsteam

bind   = $mainMod CTRL ,p ,exec ,$scrPath/awwwallpaper -p
bind   = $mainMod CTRL ,n ,exec ,$scrPath/awwwallpaper -n

bindel =       ,Prior ,exec ,playerctl position 10-
bindel =       ,Next  ,exec ,playerctl position 10+
bindl  =       ,Home  ,exec ,playerctl play-pause
bindl  =       ,End   ,exec ,playerctl play-pause
bindl  = SHIFT ,Prior ,exec ,playerctl previous
bindl  = SHIFT ,Next  ,exec ,playerctl next

bindl  =     ,F1  ,exec ,lua $scrPath/lua/darkshader.lua toggle
bindel =     ,F2  ,exec ,lua $scrPath/lua/volumecontrol.lua set Master 5 -
bindel =     ,F3  ,exec ,lua $scrPath/lua/volumecontrol.lua set Master 5 +
bindl  =     ,F4  ,exec ,lua $scrPath/lua/volumecontrol.lua set Master toggle
bindel =     ,F6  ,exec ,lua $scrPath/lua/brightnesscontrol.lua set 5 +
bindel =     ,F5  ,exec ,lua $scrPath/lua/brightnesscontrol.lua set 5 -
bind   =     ,F7  ,exec ,lua $scrPath/lua/screenshot.lua s
bind   = ALT ,F7  ,exec ,lua $scrPath/lua/screenshot.lua a
bind   =     ,F8  ,exec ,$scrPath/screenshot tx
bind   =     ,F11 ,exec ,$scrPath/recorder s
bind   = ALT ,F11 ,exec ,$scrPath/recorder sa
bind   =     ,F12 ,exec ,$scrPath/recorder m
bind   = ALT ,F12 ,exec ,$scrPath/recorder ma

bind = ,Print ,exec ,$scrPath/screenshot m

bindm = $mainMod ,mouse:272 ,movewindow
bindm = $mainMod ,mouse:273 ,resizewindow

bind = $mainMod SHIFT ,Y ,exec ,ghostty --class=com.yazi.open -e yazi
