# The basic colors
foreground              #a6adc8
background              #0e0e16
selection_foreground    #0e0e16
selection_background    #cdd6f4

color0  #0e0e16
color1  #cdd6f4
color2  #f5e0dc
color3  #cdd6f4
color4  #f5e0dc
color5  #f38ba8
color6  #f5e0dc
color7  #f5e0dc
color8  #313244
color9  #a6adc8
color10 #a6adc8
color11 #a6adc8
color12 #a6adc8
color13 #a6adc8
color14 #a6adc8
color15 #f38ba8
