themes:
  - name: "catppuccin"
    colors:
      - "#F5E0DC"
      - "#F2CDCD"
      - "#F5C2E7"
      - "#CBA6F7"
      - "#F38BA8"
      - "#EBA0AC"
      - "#FAB387"
      - "#F9E2AF"
      - "#A6E3A1"
      - "#94E2D5"
      - "#89DCEB"
      - "#74C7EC"
      - "#89B4FA"
      - "#B4BEFE"
      - "#CDD6F4"
      - "#BAC2DE"
      - "#A6ADC8"
      - "#9399B2"
      - "#7F849C"
      - "#6C7086"
      - "#585B70"
      - "#45475A"
      - "#313244"
      - "#1E1E2E"
      - "#181825"
      - "#11111B"
  - name: "dark"
    colors:
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
      - "#0e0e16"
