[mgr]
        cwd             = { fg = "#f38ba8",         bg = "black" }

        # Find
        find_keyword    = { fg = "black",           bg = "green", italic = true, bold = true }
        find_position   = { fg = "green",           bg = "black", italic = true }

        # Marker
        marker_copied   = { fg = "green",           bg = "black" }
        marker_cut      = { fg = "green",           bg = "black" }
        marker_selected = { fg = "red",             bg = "black" }

        # Count
        count_copied    = { fg = "#add8e6",         bg = "black", bold = true }
        count_cut       = { fg = "#f38ba8",         bg = "black", bold = true }
        count_selected  = { fg = "#f38ba8",         bg = "black" }

        # Border
        border_symbol   = "┃"
        # border_style    = { fg = "#1e1e2e" }
        border_style    = { fg = "black" }

        # Highlighting
        syntect_theme   = "~/.config/yazi/Catppuccin-mocha.tmTheme"

[indicator]
        parent  = { reversed = true, bold = true }
        current = { reversed = true, bold = true }
        preview = { reversed = true, bold = true }
        padding = { open = "█", close = "█" }

[tabs]
        active          = { fg = "#add8e6",         bg = "black", bold = true }
        inactive        = { fg = "#313244",         bg = "black" }
        sep_inner       = { open = "",              close = "" }
        sep_outer       = { open = "",              close = "" }
        # tab_width       = 1

[status]
        sep_left        = {open = "", close = ""}
        sep_right       = {open = "", close = ""}
        separator_style = { fg = "#313244",         bg = "black" }

[mode]
        normal_main     = { fg = "black",           bg = "red",     bold = false }
        normal_alt      = { bg = "black",           fg = "red",     bold = false }
        select_main     = { fg = "black",           bg = "green",   bold = false }
        select_alt      = { bg = "black",           fg = "green",   bold = false }
        unset_main      = { fg = "green",           bg = "#1e1e2e", bold = false }
        unset_alt       = { bg = "green",           fg = "#1e1e2e", bold = false }

        # Progress
        progress_label  = { fg = "black",           bold = true }
        progress_normal = { fg = "blue",            bg = "#1e1e2e" }
        progress_error  = { fg = "black",           bg = "#f38ba8" }

        # Permissions
        perm_type       = { fg = "#cdd6f4" }
        perm_read       = { fg = "#a6e3a1" }
        perm_write      = { fg = "#f9e2af" }
        perm_exec       = { fg = "#f38ba8" }
        perm_sep        = { fg = "#313244" }

[input]
        border          = { fg = "#a6e3a1" }
        title           = {}
        value           = {}
        selected        = { reversed = true }

[select]
        border          = { fg = "cyan" }
        active          = { fg = "cyan" }
        inactive        = {}

[tasks]
        border          = { fg = "cyan" }
        title           = {}
        hovered         = { underline = false }

[which]
        mask            = { bg = "#1e1e2e" }
        cand            = { fg = "green" }
        rest            = { fg = "#9399b2" }
        desc            = { fg = "green" }
        separator       = "  "
        separator_style = { fg = "#585b70" }

[help]
        on              = { fg = "#f5c2e7" }
        exec            = { fg = "#94e2d5" }
        desc            = { fg = "#9399b2" }
        hovered         = { bg = "#585b70",         bold = true }
        footer          = { fg = "#45475a",         bg = "white" }

[spot]
        border   = { fg = "#181825" }
        title    = { fg = "#cdd6f4" }
        tbl_col  = { fg = "#cdd6f4" }
        tbl_cell = { bg = "#11111b", reversed = false, bold = true }

[filetype]
rules = [
        { mime = "image/*",                     fg = "#f9e2af" },

        { mime = "video/*",                     fg = "#94e2d5" },
        { mime = "audio/*",                     fg = "#94e2d5" },

        { mime = "application/zip",             fg = "#f5c2e7" },
        { mime = "application/gzip",            fg = "#f5c2e7" },
        { mime = "application/tar",             fg = "#f5c2e7" },
        { mime = "application/bzip",            fg = "#f5c2e7" },
        { mime = "application/bzip2",           fg = "#f5c2e7" },
        { mime = "application/7z-compressed",   fg = "#f5c2e7" },
        { mime = "application/rar",             fg = "#f5c2e7" },

        { url = "*/" ,is = "link" ,fg = "#94e2d5" },
        { url = "*"  ,is = "link" ,fg = "#94e2d5" },
        { url = "*"  ,fg = "#6c7086" },
        { url = "*/" ,fg = "#dce0e8" },
]

[icon]
conds = [
        { if = "dir"           ,text = "", fg = "#dce0e8" },
        { if = "!(dir | link)" ,text = "", fg = "#6c7086" },
        { if = "link | dir"    ,text = "", fg = "#94e2d5" },
        { if = "link"          ,text = "", fg = "#94e2d5" },
        { if = "exec"          ,text = "", fg = "#a6e3a1" },
]

prepend_dirs = [
        { name = "Desktop"   ,text = "", fg = "#add8e6" },
        { name = "Documents" ,text = "", fg = "#f2cdcd" },
        { name = "Downloads" ,text = "", fg = "#94e2d5" },
        { name = "Pictures"  ,text = "", fg = "#f9e2af" },
        { name = "Music"     ,text = "", fg = "#cba6f7" },
        { name = "Videos"    ,text = "", fg = "#f38ba8" },
        { name = "Public"    ,text = "", fg = "#fab387" },
        { name = "hypr"      ,text = "", fg = "#89dceb" },
        { name = "nvim"      ,text = "", fg = "#a6e3a1" },
        { name = "tmux"      ,text = "", fg = "#a6e3a1" },
        # { name = "vesktop"   ,text = "", fg = "#89b4fa" },
        # { name = "ghostty"   ,text = "󰊠", fg = "#89b4fa" },
        # { name = ".config"   ,text = "", fg = "#dce0e8" },
        { name = ".config"   ,text = "", fg = "#dce0e8" },
        { name = ".local"    ,text = "", fg = "#dce0e8" },
        { name = ".cache"    ,text = "", fg = "#dce0e8" },
        { name = ".npm"      ,text = "", fg = "#dce0e8" },
        { name = ".git"      ,text = "", fg = "#dce0e8" },
]

prepend_files = [
        { name = "go.mod"         ,text = "󰟓" ,fg = "#74c7ec"},
        { name = "go.sum"         ,text = "󰟓" ,fg = "#74c7ec"},
        { name = ".gitignore"     ,text = "" ,fg = "#f38ba8"},
        { name = ".gitmodules"    ,text = "" ,fg = "#f38ba8"},
        { name = ".gitconfig"     ,text = "" ,fg = "#f38ba8"},
        { name = ".gitattributes" ,text = "" ,fg = "#f38ba8"},
        { name = ".bashrc"        ,text = "" ,fg = "#a6e3a1"},
        { name = ".bash_profile"  ,text = "" ,fg = "#a6e3a1"},
        { name = ".zshrc"         ,text = "" ,fg = "#a6e3a1"},
        { name = "zshenv"         ,text = "" ,fg = "#a6e3a1"},
        { name = "zprofile"       ,text = "" ,fg = "#a6e3a1"},
        { name = "vimrc"          ,text = "" ,fg = "#a6e3a1"},
]

exts = [
        { name = "md"  ,text = "󰍔" ,fg = "#dce0e8"},
        { name = "txt" ,text = "" ,fg = "#a6e3a1"},
        { name = "bak" ,text = "󰁯" ,fg = "#fab387"},

        { name = "zip" ,text = "" ,fg = "#fab387"},
        { name = "tar" ,text = "" ,fg = "#fab387"},
        { name = "gz"  ,text = "" ,fg = "#fab387"},
        { name = "7z"  ,text = "" ,fg = "#fab387"},
        { name = "rar" ,text = "" ,fg = "#fab387"},

        { name = "mp3"  ,text = "" ,fg = "#cba6f7"},
        { name = "flac" ,text = "" ,fg = "#cba6f7"},
        { name = "wav"  ,text = "" ,fg = "#cba6f7"},

        { name = "mp4" ,text = "" ,fg = "#f38ba8"},
        { name = "mkv" ,text = "" ,fg = "#f38ba8"},
        { name = "avi" ,text = "" ,fg = "#f38ba8"},
        { name = "mov" ,text = "" ,fg = "#f38ba8"},

        { name = "jpg"  ,text = "" ,fg = "#cba6f7"},
        { name = "jpeg" ,text = "" ,fg = "#cba6f7"},
        { name = "png"  ,text = "" ,fg = "#cba6f7"},
        { name = "gif"  ,text = "" ,fg = "#cba6f7"},
        { name = "webp" ,text = "" ,fg = "#cba6f7"},
        { name = "avif" ,text = "" ,fg = "#cba6f7"},
        { name = "bmp"  ,text = "" ,fg = "#cba6f7"},
        { name = "ico"  ,text = "" ,fg = "#cba6f7"},
        { name = "svg"  ,text = "" ,fg = "#cba6f7"},

        { name = "c"     ,text = "" ,fg = "#74c7ec"},
        { name = "cpp"   ,text = "" ,fg = "#74c7ec"},
        { name = "h"     ,text = "" ,fg = "#cba6f7"},
        { name = "hpp"   ,text = "" ,fg = "#cba6f7"},
        { name = "rs"    ,text = "" ,fg = "#eba0ac"},
        { name = "go"    ,text = "󰟓" ,fg = "#74c7ec"},
        { name = "py"    ,text = "" ,fg = "#f9e2af"},
        { name = "js"    ,text = "" ,fg = "#f9e2af"},
        { name = "ts"    ,text = "󰛦" ,fg = "#89b4fa"},
        { name = "tsx"   ,text = "" ,fg = "#94e2d5"},
        { name = "jsx"   ,text = "" ,fg = "#94e2d5"},
        { name = "rb"    ,text = "" ,fg = "#f38ba8"},
        { name = "php"   ,text = "" ,fg = "#b4befe"},
        { name = "java"  ,text = "󰬷" ,fg = "#f38ba8"},
        { name = "sh"    ,text = "" ,fg = "#a6e3a1"},
        { name = "zsh"   ,text = "" ,fg = "#a6e3a1"},
        { name = "fish"  ,text = "" ,fg = "#a6e3a1"},
        { name = "swift" ,text = "" ,fg = "#fab387"},
        { name = "vim"   ,text = "" ,fg = "#a6e3a1"},
        { name = "lua"   ,text = "" ,fg = "#89b4fa"},
        { name = "html"  ,text = "" ,fg = "#f38ba8"},
        { name = "css"   ,text = "" ,fg = "#89b4fa"},
        { name = "scss"  ,text = "" ,fg = "#89b4fa"},
        { name = "json"  ,text = "" ,fg = "#f9e2af"},
        { name = "jsonc" ,text = "" ,fg = "#f9e2af"},
        { name = "toml"  ,text = "" ,fg = "#f38ba8"},
        { name = "yml"   ,text = "" ,fg = "#a6e3a1"},
        { name = "yaml"  ,text = "" ,fg = "#a6e3a1"},
        { name = "ini"   ,text = "" ,fg = "#6c7086"},
        { name = "conf"  ,text = "" ,fg = "#6c7086"},
        { name = "v"     ,text = "󰍛" },
        { name = "sv"    ,text = "󰍛" },
        { name = "svh"   ,text = "󰍛" },
        { name = "tcl"   ,text = "󰛓" },
]
