# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Progress Dialog — Dolphin)$
windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Copying — Dolphin)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float on, match:class ^(librewolf)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(librewolf)$, match:title ^(Library)$

windowrule = float on, match:class vlc
windowrule = float on, match:class kvantummanager
windowrule = float on, match:class qt5ct
windowrule = float on, match:class qt6ct
windowrule = float on, match:class nwg-look
windowrule = float on, match:class org.kde.ark
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-applet
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class org.kde.polkit-kde-authentication-agent-1
windowrule = float on, match:class wev

# Dialogs
windowrule = float on, match:title (Select|Open)( a)? (File|Folder)(s)?
windowrule = float on, match:title File (Operation|Upload)( Progress)?
windowrule = float on, match:title .* Properties
windowrule = float on, match:title Export Image as PNG
windowrule = float on, match:title GIMP Crash Debug
windowrule = float on, match:title Save As
windowrule = float on, match:title Library

windowrule = float on, match:class Signal
windowrule = float on, match:class com.github.rafostar.Clapper
windowrule = float on, match:class app.drey.Warp
windowrule = float on, match:class net.davidotek.pupgui2
windowrule = float on, match:class yad
windowrule = float on, match:class eog
windowrule = float on, match:class io.github.alainm23.planify
windowrule = float on, match:class io.gitlab.theevilskeleton.Upscaler
windowrule = float on, match:class com.github.unrud.VideoDownloader
windowrule = float on, match:class io.gitlab.adhami3310.Impression

windowrule = group deny, no_blur on, match:float 1
windowrule = no_blur on, match:float false
windowrule = no_dim on, opacity 0.5 override 0.5 override 0.5 override, match:class com.q.bg
windowrule = group deny, float on, size 540 380, pin on, match:title Картинка в картинке
windowrule = group deny, float on, size 720 380, pin on, match:class hyprland-share-picker
windowrule = group deny, float on, size 650 340, move ((monitor_w*0.35)) (44), pin on, match:class org.pulseaudio.pavucontrol
windowrule = group deny, float on, size 460 270, pin on, match:title Discord Popout
windowrule = render_unfocused on, match:class kitty-bg

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

# layerrule = match:rofi ,blur
# layerrule = match:rofi ,ignorezero
layerrule = match:namespace rofi, dim_around on
# layerrule = match:notifications ,blur
# layerrule = match:notifications ,ignorezero
# layerrule = match:notifications ,dimaround
layerrule = match:namespace notifications, no_screen_share on
# layerrule = match:swaync-notification-window ,blur
# layerrule = match:swaync-notification-window ,ignorezero
# layerrule = match:swaync-notification-window ,dimaround
# layerrule = match:swaync-control-center      ,blur
# layerrule = match:swaync-control-center      ,ignorezero
layerrule = match:namespace swaync-control-center, dim_around on
# layerrule = match:logout_dialog              ,blur
layerrule = match:namespace hyprpicker, animation fade in
