
[urgency_low]
    background = "#656DA3FF"
    foreground = "#CCD3FFFF"
    frame_color = "#656DA303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A416BFF"
    foreground = "#CCD4FFFF"
    frame_color = "#3A416B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
