-- exec = gsettings set org.gnome.desktop.interface gtk-theme    "catppuccin-mocha-red-standard+default"
-- exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
--
-- exec = hyprctl setcursor catppuccin-mocha-red 20
-- exec = gsettings set org.gnome.desktop.interface cursor-theme catppuccin-mocha-red
-- exec = gsettings set org.gnome.desktop.interface cursor-size  20
--
-- exec = gsettings set org.gnome.desktop.interface font-name           "Monocraft 10"
-- exec = gsettings set org.gnome.desktop.interface document-font-name  "Monocraft 10"
-- exec = gsettings set org.gnome.desktop.interface monospace-font-name "Monocraft 10"
-- exec = gsettings set org.gnome.desktop.interface font-antialiasing   "rgba"
-- exec = gsettings set org.gnome.desktop.interface font-hinting        "full"
--

