#-- PLUGINS --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"

#-- PREFIX ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

set-option -g prefix \'
unbind     C-b
bind-key   \' send-prefix

#-- OPTIONS --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

set -gq terminal-overrides[1] "*:Tc"
set -gq terminal-features[3]  "xterm-ghostty:RGB"

set -g allow-passthrough on
set -g default-terminal  "tmux-256color"
set -g visual-activity   off
set -g default-terminal  "tmux-256color"
set -g mouse             on
set -g set-clipboard     on
set -g renumber-windows  on
set -g base-index        1
set -g pane-base-index   1
set -g status            off
set -g status-keys       vi
set -g status-interval   1
set -g status-justify    left
set -g status-position   bottom

setw -g automatic-rename on
setw -g mode-keys        vi

set-option -g focus-events    on
set-option -g allow-rename    on
# set-option -g terminal-features 'xterm*extkeys'
set-option -g renumber-windows on
set-option -g xterm-keys       on

set-window-option -g pane-base-index  1

#-- KEYMAPS --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

unbind r
bind   r source-file ~/.config/tmux/tmux.conf

#-- COPY MODE ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

bind -T copy-mode-vi "v"   send -X begin-selection
bind -T copy-mode-v  "C-v" send -X rectaingle-toggle
# bind -T copy-mode-v  "y"   send -X copy-selection-and-cancel
bind-key -T copy-mode-vi  y send-keys -X copy-pipe-and-cancel "wl-copy"

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

run "~/.tmux/plugins/tpm/tpm"
