local M = {}
------------------------------------------------------------------------------------------------------------------------

local squareFilled = "■"
local squareEmpty  = "󰝣"

---@enum DIAGNOSTICS
M.diagnostics = {
        ERROR = squareFilled,
        WARN  = squareFilled,
        INFO  = squareFilled,
        HINT  = squareFilled,

        Error = squareFilled,
        Warn  = squareFilled,
        Info  = squareFilled,
        Hint  = squareFilled,

        errorMd = "󰅙 ",
        warnMd  = " ",
        infoMd  = "󰀨 ",
        hintMd  = "󰁨 ",

        lightbulb = "󱠀",
}

---@enum NOTIFIER
M.notifier = {
        error = M.diagnostics.ERROR,
        warn  = M.diagnostics.WARN,
        info  = M.diagnostics.INFO,
        debug = M.diagnostics.HINT,
        trace = M.diagnostics.HINT,
}

---@enum FOLDING
M.arrows = {
        close      = "+",
        open       = "-",
        -- close = "󰜄",
        -- open  = "󰛲",
        right      = "",
        left       = "",
        up         = "",
        down       = "",
        leftArrow  = "<",
        rightArrow = ">",
}

---@enum LSP KINDS
M.symbolKinds = {
        Array             = "󰅪",
        Boolean           = "",
        BreakStatement    = "󰙧",
        Call              = "󰃷",
        CaseStatement     = "󱃙",
        Class             = "",
        Color             = "",
        Component         = "󰅴",
        Constant          = "",
        Constructor       = "",
        ContinueStatement = "→",
        Copilot           = "",
        Declaration       = "󰙠",
        Delete            = "󰢤",
        DoStatement       = "󰑖",
        Enum              = "",
        EnumMember        = "",
        Event             = "",
        Field             = "",
        File              = "",
        Folder            = "",
        ForStatement      = "󰑖",
        Fragment          = "󰅴",
        Function          = "",
        H1Marker          = "󰉫",
        H2Marker          = "󰉬",
        H3Marker          = "󰉭",
        H4Marker          = "󰉮",
        H5Marker          = "󰉯",
        H6Marker          = "󰉰",
        Identifier        = "",
        IfStatement       = "",
        Interface         = "",
        Key               = "",
        Keyword           = "",
        List              = "󰅪",
        Log               = "",
        Lsp               = "",
        Macro             = "",
        MarkdownH1        = "󰉫",
        MarkdownH2        = "󰉬",
        MarkdownH3        = "󰉭",
        MarkdownH4        = "󰉮",
        MarkdownH5        = "󰉯",
        MarkdownH6        = "󰉰",
        Method            = "",
        Module            = "",
        Namespace         = "",
        Null              = "󰢤",
        Number            = "󰎠",
        Object            = "",
        Operator          = "",
        Package           = "",
        Pair              = "󰅪",
        Parameter         = "󰏪",
        Property          = "",
        Reference         = "",
        Regex             = "",
        Repeat            = "󰑖",
        Scope             = "",
        Snippet           = "",
        Specifier         = "󰦪",
        Statement         = "",
        StaticMethod      = "",
        String            = "󰉾",
        Struct            = "",
        SwitchStatement   = "󰺟",
        Terminal          = "",
        Text              = "",
        Type              = "",
        TypeAlias         = "",
        TypeParameter     = "",
        Unit              = "",
        Value             = "",
        Variable          = "",
        WhileStatement    = "󰑖",
}

M.symbolKindsAlt = {
        Text          = "󰉿",
        Method        = "󰊕",
        Function      = "󰊕",
        Constructor   = "󰒓",
        Field         = "󰜢",
        Variable      = "󰆦",
        Property      = "󰖷",
        Class         = "󱡠",
        Interface     = "󱡠",
        Struct        = "󱡠",
        Module        = "󰅩",
        Unit          = "󰪚",
        Value         = "󰦨",
        Enum          = "󰦨",
        EnumMember    = "󰦨",
        Keyword       = "󰻾",
        Constant      = "󰏿",
        Snippet       = "󱄽",
        Color         = "󰏘",
        File          = "󰈔",
        Reference     = "󰬲",
        Folder        = "󰉋",
        Event         = "󱐋",
        Operator      = "󰪚",
        Type          = "󰜁",
        TypeParameter = "󰬛",

}

---@enum DEVICONS
M.devicons = {
        Array             = "󰅪 ",
        Boolean           = " ",
        BreakStatement    = "󰙧 ",
        Call              = "󰃷 ",
        CaseStatement     = "󱃙 ",
        Class             = " ",
        Color             = " ",
        Constant          = " ",
        Constructor       = " ",
        ContinueStatement = "→ ",
        Copilot           = " ",
        Declaration       = "󰙠 ",
        Delete            = "󰢤 ",
        DoStatement       = "󰑖 ",
        Enum              = " ",
        EnumMember        = " ",
        Event             = " ",
        Field             = " ",
        File              = " ",
        Folder            = " ",
        ForStatement      = "󰑖 ",
        Function          = " ",
        H1Marker          = "󰉫 ",
        H2Marker          = "󰉬 ",
        H3Marker          = "󰉭 ",
        H4Marker          = "󰉮 ",
        H5Marker          = "󰉯 ",
        H6Marker          = "󰉰 ",
        Identifier        = " ",
        IfStatement       = " ",
        Interface         = " ",
        Keyword           = " ",
        List              = "󰅪 ",
        Log               = " ",
        Lsp               = " ",
        Macro             = " ",
        MarkdownH1        = "󰉫 ",
        MarkdownH2        = "󰉬 ",
        MarkdownH3        = "󰉭 ",
        MarkdownH4        = "󰉮 ",
        MarkdownH5        = "󰉯 ",
        MarkdownH6        = "󰉰 ",
        Method            = " ",
        Module            = " ",
        Namespace         = " ",
        Null              = "󰢤 ",
        Number            = "󰎠 ",
        Object            = " ",
        Operator          = "󰆕 ",
        Package           = " ",
        Pair              = "󰅪 ",
        Property          = " ",
        Reference         = "󰈇 ",
        Regex             = " ",
        Repeat            = "󰑖 ",
        Scope             = " ",
        Snippet           = " ",
        Specifier         = "󰦪 ",
        Statement         = " ",
        String            = "󰉾 ",
        Struct            = " ",
        SwitchStatement   = "󰺟 ",
        Terminal          = " ",
        Text              = " ",
        Type              = " ",
        TypeParameter     = " ",
        Unit              = " ",
        Value             = "󰎠 ",
        Variable          = " ",
        WhileStatement    = "󰑖 ",
}

---@enum MISC
M.misc = {
        Bug            = "",
        ellipsis       = "…",
        Search         = "",
        Vertical_bar   = "▏",
        Prompt         = ">",
        folderOpen     = "",
        folderEmpty    = "",
        reference      = "󰘷",
        implementation = "󰃐",
        offSpec        = "",
        dashedBar      = squareFilled,
        definiton      = squareFilled,
        squareFilled   = squareFilled,
        squareEmpty    = squareEmpty,
}

---@enum BORDERS
M.borders = {
        empty = { " ", " ", " ", " ", " ", " ", " ", " " },
}

---@enum SPINNER
M.spinner = {
        dots     = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
        vertical = { "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" },
}

---@enum GIT
M.git = {
        Git      = "",
        Added    = squareFilled,
        Modified = squareEmpty,
        Deleted  = squareEmpty,
}

------------------------------------------------------------------------------------------------------------------------
return M
