source = ~/.config/hypr/colors.conf

$x  = -200
$y  = 0
$x1 = -200
$y1 = 20
$x2 = -200
$y2 = -40

shape {
        color    = $lockBg
        size     = 360, 160
        position = $x, $y
        halign   = center
        valign   = center
}

# TIME
label {
        text                = cmd[update:1000] echo -e "<span>$(date +"%H:%M")</span>"
        font_size           = 60
        color               = $lockRed
        font_family         = Monocraft
        position            = $x1, $y1
        halign              = center
        valign              = center
}

# DATE
label {
        text                = cmd[update:1000] echo -e "$(date +"%a %d·%m·%y")"
        color               = $lockIvory
        font_size           = 20
        font_family         = Monocraft
        position            = $x2, $y2
        halign              = center
        valign              = center
}

