background {
        monitor             =
        blur_passes         = 2
        noise               = 0.0
        path                = screenshot
}

general {
        no_fade_in          = true
        grace               = 0
        disable_loading_bar = false
        ignore_empty_input  = true
}
