source = ~/.config/hypr/colors.conf
$font = Monocraft

$x = 180
$y = -50

input-field {
        size                = 380, 60
        outline_thickness   = 0
        dots_size           = 0.2 # Scale of input-field height, 0.2 - 0.8
        dots_spacing        = 1.0 # Scale of dots' absolute size, 0.0 - 1.0
        dots_rounding       = -4
        dots_center         = true
        rounding            = 0
        outer_color         = $lockBg
        inner_color         = $lockBg
        check_color         = $lockBg
        fail_color          = $lockRed
        font_color          = $lockRed
        fail_text           = Skill Issue
        fade_on_empty       = false
        font_family         = $font
        placeholder_text    = <i></i>
        hide_input          = false
        position            = $x, $y
        halign              = center
        valign              = center
}
