source = ~/.config/hypr/colors.conf
$script_path = ~/.config/hypr/hyprlock
$font = Monocraft

$bg  = rgb(17, 17, 27)

$x  = -200
$y  = 170
$x1 = -340
$y1 = 190
$x2 = -180
$y2 = 190
$x3 = -200
$y3 = 130

shape {
        color    = $lockBg
        size     = 360, 160
        position = $x, $y
        halign   = center
        valign   = center
}

# Media source symbol
label {
        text        = cmd[update:10000] $script_path/player -s
        text_align  = center
        color       = $lockRed
        font_size   = 14
        font_family = $font
        position    = $x1, $y1
        halign      = center
        valign      = center
        zindex      = 3
}

# Media playing
label {
        text        = cmd[update:10000] $script_path/player -n
        text_align  = center
        color       = $lockRed
        font_size   = 16
        font_family = $font
        position    = $x2, $y2
        halign      = center
        valign      = center
        zindex      = 3
}

# Name of player/artist
label {
        text        = cmd[update:10000] $script_path/player -a
        text_align  = center
        color       = $lockRed
        font_size   = 14
        font_family = $font
        position    = $x3, $y3
        halign      = center
        valign      = center
        zindex      = 3
}

